name: Bug report
description: Report technical issues (bugs)
body:

- type: markdown
  attributes:
    value: |
      **IMPORTANT**
      Please only submit technical bug reports here. This is not a place to make feature requests or suggestions.

- type: textarea
  attributes:
    label: Describe the bug
    placeholder: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behaviour.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Play and do '...'
      4. See error
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen, instead of what actually happened.
  validations:
    required: true

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false

- type: textarea
  attributes:
    label: System information
    description: >
      Please specify the OS version, GPU info for graphics-related issues,
      and your Thrive version. You can find GPU info in the game logs.
    placeholder: |
      - OS: Windows 11
      - Browser: Chrome 133.0.6943.143 
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context about the problem here.
  validations:
    required: false
